version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: ex23_back
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
    container_name: ex23_front
    ports:
      - 5000:5000
    depends_on: 
      - backend