version: '3'

services:
  backend:
    image: ex23_backend
    container_name: ex29_back
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=ex29
      - DB_PASSWORD=
      - DB_NAME=ex29
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  frontend:
    image: ex23_frontend
    container_name: ex29_front
    ports:
      - 5000:5000
    depends_on: 
      - backend
  redis:
    image: redis
    container_name: ex29_redis
  db:
    image: postgres
    environment:
      - POSTGRES_USER=ex29
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=ex29
    volumes:
      - /home/syyspe/data:/var/lib/postgresql/data
    container_name: ex29_psql
