version: '3'

services:
  backend:
    image: ex23_backend
    container_name: ex28_back
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=ex28
      - DB_PASSWORD=
      - DB_NAME=ex28
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  frontend:
    image: ex23_frontend
    container_name: ex28_front
    ports:
      - 5000:5000
    depends_on: 
      - backend
  redis:
    image: redis
    container_name: ex28_redis
  db:
    image: postgres
    environment:
      - POSTGRES_USER=ex28
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=ex28
    container_name: ex28_psql
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: ex28_nginx
    depends_on:
      - frontend
      - backend
